---
- name: Create share directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: sambashare
    mode: "{{ '0775' if item == '/public' else '0770' }}"
  loop:
    - /public
    - /internal

- name: Backup original smb.conf
  copy:
    src: /etc/samba/smb.conf
    dest: /etc/samba/smb.conf.bak
    remote_src: yes
  ignore_errors: yes

- name: Deploy new smb.conf
  template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: '0644'
