---
- name: Copy certificates to grading directory
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    remote_src: yes
  loop:
    - { src: "{{ ca_base_dir }}/certs/ca.crt", dest: "{{ grading_dir }}/ca.pem" }
    - { src: "{{ ca_base_dir }}/certs/mail.crt", dest: "{{ grading_dir }}/mail.pem" }
    - { src: "{{ ca_base_dir }}/certs/web.crt", dest: "{{ grading_dir }}/web.pem" }
    - { src: "{{ ca_base_dir }}/certs/subca.crt", dest: "{{ grading_dir }}/services.pem" }
