---
- name: Generate Sub CA certificate signing request
  command: >
    openssl req -new -nodes 
    -key {{ ca_base_dir }}/private/subca.key 
    -out {{ ca_base_dir }}/subca.csr
    -subj "/C=FR/O=ClearSky/CN=ClearSky Sub CA"
  args:
    creates: "{{ ca_base_dir }}/subca.csr"

- name: Sign Sub CA certificate with Root CA
  command: >
    openssl ca -batch
    -config /etc/ssl/openssl.cnf 
    -extensions v3_intermediate_ca 
    -policy policy_anything 
    -in {{ ca_base_dir }}/subca.csr 
    -out {{ ca_base_dir }}/certs/subca.crt
  args:
    creates: "{{ ca_base_dir }}/certs/subca.crt"

- name: Create extension file for web certificate
  template:
    src: web.ext.j2
    dest: "{{ ca_base_dir }}/web.ext"

- name: Generate web server private key
  command: openssl genrsa -out {{ ca_base_dir }}/private/web.key 2048
  args:
    creates: "{{ ca_base_dir }}/private/web.key"

- name: Set permissions on web server private key
  file:
    path: "{{ ca_base_dir }}/private/web.key"
    mode: '0600'

- name: Generate web server certificate signing request
  command: >
    openssl req -new -nodes 
    -key {{ ca_base_dir }}/private/web.key 
    -out {{ ca_base_dir }}/web.csr
    -subj "/C=FR/O=ClearSky/CN=www.dmz.worldskills.org"
  args:
    creates: "{{ ca_base_dir }}/web.csr"

- name: Sign web server certificate with Root CA
  command: >
    openssl x509 -req 
    -in {{ ca_base_dir }}/web.csr 
    -out {{ ca_base_dir }}/certs/web.crt 
    -CA {{ ca_base_dir }}/certs/ca.crt 
    -CAkey {{ ca_base_dir }}/private/ca.key 
    -CAcreateserial 
    -sha256 
    -days 3650 
    -extensions req_ext 
    -extfile {{ ca_base_dir }}/web.ext
  args:
    creates: "{{ ca_base_dir }}/certs/web.crt"

- name: Create extension file for mail certificate
  template:
    src: mail.ext.j2
    dest: "{{ ca_base_dir }}/mail.ext"

- name: Generate mail server private key
  command: openssl genrsa -out {{ ca_base_dir }}/private/mail.key 2048
  args:
    creates: "{{ ca_base_dir }}/private/mail.key"

- name: Set permissions on mail server private key
  file:
    path: "{{ ca_base_dir }}/private/mail.key"
    mode: '0600'

- name: Generate mail server certificate signing request
  command: >
    openssl req -new -nodes 
    -key {{ ca_base_dir }}/private/mail.key 
    -out {{ ca_base_dir }}/mail.csr
    -subj "/C=FR/O=ClearSky/CN=mail.dmz.worldskills.org"
  args:
    creates: "{{ ca_base_dir }}/mail.csr"

- name: Sign mail server certificate with Root CA
  command: >
    openssl x509 -req 
    -in {{ ca_base_dir }}/mail.csr 
    -out {{ ca_base_dir }}/certs/mail.crt 
    -CA {{ ca_base_dir }}/certs/ca.crt 
    -CAkey {{ ca_base_dir }}/private/ca.key 
    -CAcreateserial 
    -sha256 
    -days 3650 
    -extensions req_ext 
    -extfile {{ ca_base_dir }}/mail.ext
  args:
    creates: "{{ ca_base_dir }}/certs/mail.crt"
