---
- name: Configure Transparent Proxy on fw
  hosts: fw

  vars:
    squid_conf_path: /etc/squid/squid.conf
    nftables_conf_path: /etc/nftables.conf
    squid_config: |
      http_port 3128
      http_port 3129 intercept
      http_access allow all
      reply_header_add X-Secured-By clearsky-proxy
      visible_hostname fw.worldskills.org

    nftables_config: |
      table ip nat {
        chain prerouting {
          type nat hook prerouting priority dstnat;
          policy accept;
          iif { "ens36", "ens37" } tcp dport 80 redirect to :3129;
        }
      }

      table ip6 nat {
        chain prerouting {
          type nat hook prerouting priority dstnat;
          policy accept;
          iif { "ens36", "ens37" } tcp dport 80 redirect to :3129;
        }
      }

  tasks:
    - name: Install squid
      apt:
        name: squid
        state: present
        update_cache: yes

    - name: Configure squid.conf
      copy:
        dest: "{{ squid_conf_path }}"
        content: "{{ squid_config }}"
        owner: root
        group: root
        mode: '0644'

    - name: Restart squid
      systemd:
        name: squid
        state: restarted
        enabled: yes

    - name: Configure nftables.conf
      copy:
        dest: "{{ nftables_conf_path }}"
        content: "{{ nftables_config }}"
        owner: root
        group: root
        mode: '0644'

    - name: Restart nftables service
      systemd:
        name: nftables
        state: restarted
        enabled: yes
